version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'skipthequeue'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  redis-server:
    restart: always
    image: redis:4.0
    ports:
      - "6379:6379"
