name: CI

on:
  push:
    branches:
    - master
    - develop
    - release/*

  pull_request:
    branches:
    - master
    - develop
    - release/*

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v1
        with:
          java-version: "11"
      - name: Build Docker Image
        run: mvn package
      - name: Publish to Docker Hub
        run: |
          docker login --username=${{ secrets.TREESCALE_USERNAME }} --password=${{ secrets.TREESCALE_PASSWORD }}
          docker push countrybroot/backend:latest
