name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v1
        with:
          java-version: "11"
      - name: Build with Maven
        run: mvn package && mvn dockerfile:build
      - name: Docker build
        run: |
          docker login --username=${{ secrets.TREESCALE_USERNAME }} --password=${{ secrets.TREESCALE_PASSWORD }}
          docker push countrybroot/backend
